### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by doguaraci** [TamasBarta/obsidian-spotify-embed#1] opened 2021-12-05 10:19 UTC
Hi I get the following error message when I try to activate the spotify-embed. 

```
Plugin failure: obsidian-spotify-embed SyntaxError: Cannot use import statement outside a module
    at eval (<anonymous>)
    at app.js:1
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
```

**Comment by TamasBarta** [comment] 2021-12-06 16:11
Hi,

I couldn't reproduce your issue. Can you tell me more about your environment, how you installed the plugin, etc?

I left out some original installation steps described in the [template repo](https://github.com/obsidianmd/obsidian-sample-plugin), because I thought I'll revisit that sooner, and publish the plugin. The way you should install it is to clone the repo, build the plugin, and only then you'll have the `main.js` which you'll be able to copy over. The build steps are omitted from the README, but it should look like this (as described in the template repo):

```
git clone https://github.com/TamasBarta/obsidian-spotify-embed.git
cd obsidian-spotify-embed
npm i
npm run build
mkdir -p <obisidianvault>/.obsidian/plugins/obsidian-spotify-embed
cp main.js manifest.json <obisidianvault>/.obsidian/plugins/obisidian-spotify-embed/
```

I hope this helps, but it's just my assumption that it's because you copied the `main.ts` over instead of the compiled plugin.

**Comment by TamasBarta** [comment] 2023-04-16 13:49
Closing for no further clue to continue on. Feel free to provide more details, or open a new issue.

**Closed as completed by TamasBarta** 2023-04-16 13:49 UTC
